version: '3.8'

services:
  db_api:
    image: postgres:15.0-alpine
    container_name: planner-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=planner-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
